# Generated by Django 4.2.2 on 2023-10-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeclass_line_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatstatus',
            name='propagation',
            field=models.BooleanField(default=False),
        ),
    ]
